// Generated by CoffeeScript 1.11.1
(function() {
  var http, user;

  http = require('http');

  user = require('./user.coffee');

  http.createServer(function(req, res) {
    return user.get('Geoff', function(id) {
      res.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      return res.end('Salut ' + id + ' comment vas-tu ?');
    });
  }).listen(3300, '127.0.0.1');

}).call(this);
